### ISSUE TITLE
Reduce number of tasks needed to be defined

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-docs#5]
I left a comment somewhere in one of the PRs... and can't find it now.

The thing is that we shouldn't need to define 5 tasks just to register the `docs` one. All other tasks are unnecessary.

We found a way how to do that – see https://github.com/ckeditor/ckeditor5-dev-utils/issues/21 and interpret it as – the dev-docs package should expose a function (called `docs()`) which runs the other sub tasks internally. The other sub tasks can also be exposed if anyone would like to use them for any weird reason. However, don't expose too much.

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/34.
