### ISSUE TITLE
Option for turning on the links validator

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev-docs#6]
Related to: https://github.com/cksource/docs-builder/issues/29

We need some option which allows turning on the links validator. For example:

```
gulp docs --check-links
```

It means during the build, all the links will be checked (whether they are correct, direct to proper destination).

**Comment by pomek** [comment]
I'm wondering whether do something on the opposite side. I mean, by default we will check all the links but we can turn off this just by the option.

**Comment by Reinmar** [comment]
This option should be on by default and I don't see why would anyone want to turn it off. So it doesn't make sense to add any option actually. It's an obligatory test.

**Comment by pomek** [comment]
Hm. It makes sense. So, this ticket is no longer valid.
